#!/bin/bash
clear
make soda 
seed=$((1 + $RANDOM))
echo "seed is" $seed
./soda d $seed
# for (( c=1; c<=1; c++ ))
# do  
#     ./soda d $seed
# done

./sodaAnswer d $seed > answer.txt

# ./soda d 5 > output.txt
# ./soda_DEBUG d 10 > output_DEBUG.txt
# ./sodaAnswer d 10 > answer.txt
